#!/bin/bash
## couchpotato/run
## vers = 227325dbbd533c608a1e4719cc59efaa

export lxcuser=$(grep "lxc-media user" /etc/passwd | cut -d : -f 1)
export lxcgroup=$(grep "$lxcuser" /etc/group | cut -d : -f 1)

cat /etc/motd
echo "[START] sickrage as user: $lxcuser:$lxcgroup"
exec chpst -u $lxcuser:$lxcgroup /opt/couchpotato/CouchPotato.py --data_dir=/config
