#!/bin/bash
## sv/headphones/run
## vers = 9f41d8b721489ba2d182843f2190a4e8

export lxcuser=$(grep "lxc-media user" /etc/passwd | cut -d : -f 1)
export lxcgroup=$(grep "$lxcuser" /etc/group | cut -d : -f 1)

cat /etc/motd
echo "[START] headphones as user: $lxcuser:$lxcgroup"
exec chpst -u $lxcuser:$lxcgroup /opt/headphones/Headphones.py --datadir=/config
