#!/bin/sh
## sabnzbd/run
## vers= 3edb737075f72f1723cd0c4ce180025f

export lxcuser=$(grep "lxc-media user" /etc/passwd | cut -d : -f 1)
export lxcgroup=$(grep "$lxcuser" /etc/group | cut -d : -f 1)
export TERM=vt100

cat /etc/motd
echo "[START] sabnzbd as user: $lxcuser:$lxcgroup"
exec chpst -u $lxcuser:$lxcgroup /opt/nzbget/nzbget -c /config/nzbget.conf -s
